[2021-02-09 12:05:57,317] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: parse_goods.run_spider_goods 2021-02-08T00:00:00+00:00 [queued]>
[2021-02-09 12:05:57,330] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: parse_goods.run_spider_goods 2021-02-08T00:00:00+00:00 [queued]>
[2021-02-09 12:05:57,330] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-02-09 12:05:57,331] {taskinstance.py:880} INFO - Starting attempt 2 of 2
[2021-02-09 12:05:57,331] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-02-09 12:05:57,347] {taskinstance.py:900} INFO - Executing <Task(BashOperator): run_spider_goods> on 2021-02-08T00:00:00+00:00
[2021-02-09 12:05:57,351] {standard_task_runner.py:53} INFO - Started process 10922 to run task
[2021-02-09 12:06:02,417] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: parse_goods.run_spider_goods 2021-02-08T00:00:00+00:00 [running]> Maxims-MacBook-Air.local
[2021-02-09 12:06:07,459] {bash_operator.py:82} INFO - Tmp dir root location: 
 /var/folders/yy/cdksfv594ms0d4n7_jss_mm40000gn/T
[2021-02-09 12:06:07,462] {bash_operator.py:105} INFO - Temporary script location: /var/folders/yy/cdksfv594ms0d4n7_jss_mm40000gn/T/airflowtmp6yd97wsk/run_spider_goodsesslwyvz
[2021-02-09 12:06:07,462] {bash_operator.py:115} INFO - Running command: #!/bin/bash

echo 1
scrapy crawl reviewsspider -o test.json
[2021-02-09 12:06:07,477] {bash_operator.py:122} INFO - Output:
[2021-02-09 12:06:07,488] {bash_operator.py:126} INFO - 1
[2021-02-09 12:06:09,008] {bash_operator.py:126} INFO - Scrapy 2.4.1 - no active project
[2021-02-09 12:06:09,009] {bash_operator.py:126} INFO - 
[2021-02-09 12:06:09,010] {bash_operator.py:126} INFO - Unknown command: crawl
[2021-02-09 12:06:09,011] {bash_operator.py:126} INFO - 
[2021-02-09 12:06:09,012] {bash_operator.py:126} INFO - Use "scrapy" to see available commands
[2021-02-09 12:06:09,107] {bash_operator.py:130} INFO - Command exited with return code 2
[2021-02-09 12:06:09,115] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/Users/maxim/PycharmProjects/airflow/venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/maxim/PycharmProjects/airflow/venv/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2021-02-09 12:06:09,130] {taskinstance.py:1187} INFO - All retries failed; marking task as FAILED.dag_id=parse_goods, task_id=run_spider_goods, execution_date=20210208T000000, start_date=20210209T090557, end_date=20210209T090609
[2021-02-09 12:06:12,474] {logging_mixin.py:112} INFO - [2021-02-09 12:06:12,472] {local_task_job.py:103} INFO - Task exited with return code 1
