[2021-02-22 03:04:31,740] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: parse_goods.telegram_send_report 2021-02-21T00:00:00+00:00 [queued]>
[2021-02-22 03:04:31,757] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: parse_goods.telegram_send_report 2021-02-21T00:00:00+00:00 [queued]>
[2021-02-22 03:04:31,757] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-02-22 03:04:31,757] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2021-02-22 03:04:31,758] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-02-22 03:04:31,774] {taskinstance.py:900} INFO - Executing <Task(BashOperator): telegram_send_report> on 2021-02-21T00:00:00+00:00
[2021-02-22 03:04:31,778] {standard_task_runner.py:53} INFO - Started process 39185 to run task
[2021-02-22 03:04:36,851] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: parse_goods.telegram_send_report 2021-02-21T00:00:00+00:00 [running]> Maxims-MacBook-Air.local
[2021-02-22 03:04:41,884] {bash_operator.py:82} INFO - Tmp dir root location: 
 /var/folders/yy/cdksfv594ms0d4n7_jss_mm40000gn/T
[2021-02-22 03:04:41,886] {bash_operator.py:105} INFO - Temporary script location: /var/folders/yy/cdksfv594ms0d4n7_jss_mm40000gn/T/airflowtmpfyp1vzex/telegram_send_reportwo4csb64
[2021-02-22 03:04:41,886] {bash_operator.py:115} INFO - Running command: #!/bin/bash

cd /Users/maxim/PycharmProjects/airflow/dags/telegram
python telegram.py
[2021-02-22 03:04:41,897] {bash_operator.py:122} INFO - Output:
[2021-02-22 03:43:47,027] {logging_mixin.py:112} INFO - [2021-02-22 03:43:47,022] {local_task_job.py:114} ERROR - Heartbeat time limited exceeded!
[2021-02-22 03:43:47,897] {helpers.py:325} INFO - Sending Signals.SIGTERM to GPID 39185
[2021-02-22 03:43:47,898] {taskinstance.py:954} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-02-22 03:43:47,997] {bash_operator.py:140} INFO - Sending SIGTERM signal to bash process group
[2021-02-22 03:43:48,249] {helpers.py:291} INFO - Process psutil.Process(pid=39201, status='terminated') (39201) terminated with exit code None
[2021-02-22 03:43:48,273] {taskinstance.py:1145} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/Users/maxim/PycharmProjects/airflow/venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/maxim/PycharmProjects/airflow/venv/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 124, in execute
    for line in iter(self.sub_process.stdout.readline, b''):
  File "/Users/maxim/PycharmProjects/airflow/venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 956, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-02-22 03:43:48,355] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2021-02-22 03:43:48,421] {helpers.py:291} INFO - Process psutil.Process(pid=39185, status='terminated') (39185) terminated with exit code 1
[2021-02-22 03:43:48,422] {helpers.py:291} INFO - Process psutil.Process(pid=39200, status='terminated') (39200) terminated with exit code None
