[2021-02-22 04:55:15,322] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: parse_goods.telegram_send_report 2021-02-21T00:00:00+00:00 [queued]>
[2021-02-22 04:55:15,340] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: parse_goods.telegram_send_report 2021-02-21T00:00:00+00:00 [queued]>
[2021-02-22 04:55:15,340] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-02-22 04:55:15,340] {taskinstance.py:880} INFO - Starting attempt 2 of 2
[2021-02-22 04:55:15,340] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-02-22 04:55:15,351] {taskinstance.py:900} INFO - Executing <Task(BashOperator): telegram_send_report> on 2021-02-21T00:00:00+00:00
[2021-02-22 04:55:15,353] {standard_task_runner.py:53} INFO - Started process 39460 to run task
[2021-02-22 04:55:20,876] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: parse_goods.telegram_send_report 2021-02-21T00:00:00+00:00 [running]> Maxims-MacBook-Air.local
[2021-02-22 04:55:25,905] {bash_operator.py:82} INFO - Tmp dir root location: 
 /var/folders/yy/cdksfv594ms0d4n7_jss_mm40000gn/T
[2021-02-22 04:55:25,907] {bash_operator.py:105} INFO - Temporary script location: /var/folders/yy/cdksfv594ms0d4n7_jss_mm40000gn/T/airflowtmpkxq4gej6/telegram_send_reportutwwv5iq
[2021-02-22 04:55:25,907] {bash_operator.py:115} INFO - Running command: #!/bin/bash

cd /Users/maxim/PycharmProjects/airflow/dags/telegram
python telegram.py
[2021-02-22 04:55:25,976] {bash_operator.py:122} INFO - Output:
[2021-02-22 06:08:41,034] {logging_mixin.py:112} INFO - [2021-02-22 06:08:41,033] {local_task_job.py:114} ERROR - Heartbeat time limited exceeded!
[2021-02-22 06:08:41,812] {helpers.py:325} INFO - Sending Signals.SIGTERM to GPID 39460
[2021-02-22 06:08:41,818] {taskinstance.py:954} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-02-22 06:08:41,820] {bash_operator.py:140} INFO - Sending SIGTERM signal to bash process group
[2021-02-22 06:08:41,852] {helpers.py:291} INFO - Process psutil.Process(pid=39468, status='terminated') (39468) terminated with exit code None
[2021-02-22 06:08:41,911] {taskinstance.py:1145} ERROR - Task received SIGTERM signal
Traceback (most recent call last):
  File "/Users/maxim/PycharmProjects/airflow/venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/maxim/PycharmProjects/airflow/venv/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 124, in execute
    for line in iter(self.sub_process.stdout.readline, b''):
  File "/Users/maxim/PycharmProjects/airflow/venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 956, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-02-22 06:08:42,016] {taskinstance.py:1187} INFO - All retries failed; marking task as FAILED.dag_id=parse_goods, task_id=telegram_send_report, execution_date=20210221T000000, start_date=20210222T015515, end_date=20210222T030842
[2021-02-22 06:08:42,091] {helpers.py:291} INFO - Process psutil.Process(pid=39460, status='terminated') (39460) terminated with exit code 1
[2021-02-22 06:08:42,093] {helpers.py:291} INFO - Process psutil.Process(pid=39467, status='terminated') (39467) terminated with exit code None
