[2021-02-09 11:58:39,039] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: parse_goods.run_spider_goods 2021-02-09T08:57:48.374621+00:00 [queued]>
[2021-02-09 11:58:39,053] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: parse_goods.run_spider_goods 2021-02-09T08:57:48.374621+00:00 [queued]>
[2021-02-09 11:58:39,053] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-02-09 11:58:39,053] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2021-02-09 11:58:39,053] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-02-09 11:58:39,070] {taskinstance.py:900} INFO - Executing <Task(BashOperator): run_spider_goods> on 2021-02-09T08:57:48.374621+00:00
[2021-02-09 11:58:39,074] {standard_task_runner.py:53} INFO - Started process 10561 to run task
[2021-02-09 11:58:44,154] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: parse_goods.run_spider_goods 2021-02-09T08:57:48.374621+00:00 [running]> Maxims-MacBook-Air.local
[2021-02-09 11:58:49,184] {bash_operator.py:82} INFO - Tmp dir root location: 
 /var/folders/yy/cdksfv594ms0d4n7_jss_mm40000gn/T
[2021-02-09 11:58:49,185] {bash_operator.py:105} INFO - Temporary script location: /var/folders/yy/cdksfv594ms0d4n7_jss_mm40000gn/T/airflowtmpehjyozul/run_spider_goods083ikjw8
[2021-02-09 11:58:49,186] {bash_operator.py:115} INFO - Running command: #!/bin/bash

echo 1
scrapy crawl reviewsspider -o test.json
[2021-02-09 11:58:49,200] {bash_operator.py:122} INFO - Output:
[2021-02-09 11:58:49,207] {bash_operator.py:126} INFO - 1
[2021-02-09 11:58:49,215] {bash_operator.py:126} INFO - /var/folders/yy/cdksfv594ms0d4n7_jss_mm40000gn/T/airflowtmpehjyozul/run_spider_goods083ikjw8: line 4: scrapy: command not found
[2021-02-09 11:58:49,216] {bash_operator.py:130} INFO - Command exited with return code 127
[2021-02-09 11:58:49,224] {taskinstance.py:1145} ERROR - Bash command failed
Traceback (most recent call last):
  File "/Users/maxim/PycharmProjects/airflow/venv/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/maxim/PycharmProjects/airflow/venv/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 134, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2021-02-09 11:58:49,230] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2021-02-09 11:58:54,188] {logging_mixin.py:112} INFO - [2021-02-09 11:58:54,187] {local_task_job.py:103} INFO - Task exited with return code 1
